appstore/urls.py
from django.urls import path

from .views import *

app_name = "appstore"

urlpatterns = [

    path('', HomeView.as_view(), name='home'),
    path("about/", AboutView.as_view(), name='about'),
    path("contact/", ContactView.as_view(), name='contact'),
    path("allproducts/", AllProductsView.as_view(), name='allproducts'),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name='productdetail'),
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name='addtocart'),
    path("my_cart/", MyCartView.as_view(), name='mycart'),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name='managecart'),
    path("empty-cart/", EmptyCartView.as_view(), name='emptycart'),
    path("checkout/", CheckoutView.as_view(), name='checkout'),
    path("register/", CustomerRegistrationView.as_view(), name='customerregistration'),
    path("logout/", CustomerLogoutView.as_view(), name='customerlogout'),
    path("login/", CustomerLoginView.as_view(), name='customerlogin'),
    path("profile/", CustomerProfileView.as_view(), name='customerprofile'),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(), name='customerorderdeatail'),

]

ecolocal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("appstore.urls")),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

appstore/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product")
    marked_price = models.DecimalField(max_digits=7, decimal_places=2)
    # marked_price=models.PositiveIntegerField()
    # selling_price = models.PositiveIntegerField()
    selling_price=models.DecimalField(max_digits=7, decimal_places=2)
    description = models.TextField()
    warranty = models.CharField(max_length=200, null=True, blank=True)
    return_policy = models.CharField(max_length=200, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    # total = models.PositiveIntegerField(default=0)
    total=models.DecimalField(max_digits=7, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # rate = models.PositiveIntegerField()
    rate=models.DecimalField(max_digits=7, decimal_places=2)


    quantity = models.PositiveIntegerField()
    # subtotal = models.PositiveIntegerField()
    subtotal=models.DecimalField(max_digits=7, decimal_places=2)


    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = [
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),

]


class Order(models.Model):

    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=15)
    email = models.EmailField(null=True, blank=True)
    # subtotal = models.PositiveIntegerField()
    subtotal = models.DecimalField(max_digits=7, decimal_places=2)
    discount = models.PositiveIntegerField()

    # total = models.PositiveIntegerField()
    total = models.DecimalField(max_digits=7, decimal_places=2)

    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order: " + str(self.id)

templates/about.html
{% extends "base.html" %}
{% block title %}about us{% endblock %}

{% block content %}
<h1>about us bidmi lah</h1>


{% endblock  %}

templates/addtocart.html
{% extends 'base.html' %}
{% block title %}add to cart {% endblock %}
{% block content %}
<div class="container">
<h3>add to cart successfully.</h3>


</div>
{% endblock %}

templates/allproducts.html
{% extends 'base.html' %}
{% block title %}allProducts{% endblock %}
{% block content %}
<div class="container">
<h1 >All product</h1><hr>
    {% for cat in allcategories %}
    <h4 style="background-color: cornflowerblue;color: #f60404" class="text-center m-3">{{cat.title}}</h4>

<div class="row">
{% for p in cat.product_set.all %}

    <div class="col-md-4" style="border: 1px solid lightgrey;">

<h3 style="color:tomato;"> <a href="{% url 'appstore:productdetail' p.slug    %}">{{p.title}}</a></h3>

<a href="{% url 'appstore:productdetail' p.slug    %}"><img src="{{p.image.url}}" height="200"></a>
        <p style="color:crimson" class="mt-3">Price:<strike>{{p.marked_price}}</strike></p>
<h1 style="color:#d9ff00;">{{p.selling_price}} $</h1>
<a href="{% url 'appstore:addtocart' p.id %}" class="btn btn  bg-primary">Add to cart </a>

<!--<p style="color:red;">{{p.description}}</p>-->


     </div>
    {% endfor %}


</div>
{% endfor %}
</div>
{% endblock  %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>

<!--0000000000000000000000000000000000000000000000-->

    <nav class="navbar navbar-dark bg-primary"></nav>

<!--0000000000000000000000000000000000000000000000-->











    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color: lemonchiffon">
<div class="container">
    <a href="{% url 'appstore:home'%}">home</a>|
    <a href="{% url 'appstore:about' %}">about</a>|
    <a href="{% url 'appstore:contact' %}">contact</a>|
    <a href="{% url 'appstore:allproducts' %}">allproduct</a>|
    <a href="{% url 'appstore:mycart' %}">View Cart</a>|
<!--    <a href="{% url 'appstore:customerregistration' %}">Registration</a>|-->
{%  if request.user.customer %}
    Salam Alikom<a style="color: blueviolet"> {{request.user.username}}</a>|
        <a href="{% url 'appstore:customerprofile' %}">My Profile</a>|
        <a href="{% url 'appstore:customerlogout' %}">logout</a>

    {% else %}
    <a href="{% url 'appstore:customerregistration' %}">Register</a>|
    <a href="{% url 'appstore:customerlogin' %}">Login</a>


    {% endif %}
<!--    {%  if request.user.logout %}-->
<!--    Salam Alikom {{request.user.logout}}-->
<!--    {% else %}-->
<!--    <h3 class="btn btn-danger"><a style="color: black" href="{% url 'appstore:home' %}">logout khrj</a></h3>-->
<!--    {% endif %}-->
</div>
<!--lemonchiffon-->
<hr>
{% block content %}


{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

</body>
</html>

templates/checkout.html
{% extends 'base.html' %}

{% block title %} checkout {% endblock %}
{%  block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">

            <h3>Items in the cart </h3>
            <a class="btn btn-info" href="{% url 'appstore:mycart' %}"> update quantity  </a>
             <table class="table">
                <thead>
                <tr>
                <th>SN</th>
                <th>Product</th>
                <th>Rate</th>
                <th>Quantity</th>
                <th>Subtotal</th>

                </tr>

                </thead>

                <tbody>
                {% for cp in cart.cartproduct_set.all%}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{cp.product.title}}</td>
                    <td>{{cp.rate}}</td>
                    <td>{{cp.quantity}}</td>
                    <td>{{cp.subtotal}}</td>
                </tr>
                {% endfor %}
                <tr>
                    <th colspan="4" class="text-right">Total</th>
                    <th> {{cart.total}} dh</th>
                </tr>
                </tbody>
             </table>

        </div>
        <div class="col-md-6">

            <h3>checkout form </h3>
            <form action="" method="POST">
                {% csrf_token  %}
                {{ form.as_p }}
                <button class="btn btn-info">Place order</button>

            </form>
        </div>

    </div>

</div>
{%  endblock  %}

templates/contact.html
{% extends "base.html" %}
{% block title %}contact us{% endblock %}
{% block content %}

<h1>this is our contact</h1>
<p>0610+4444848</p>
<p>0610+4444848</p>
<p>0610+4444848</p>
{% endblock  %}

templates/customerlogin.html
{% extends 'base.html' %}
{% block title %}Login{% endblock  %}
{% block content%}
<style>
   .errorlist{

       color: #f60404;
       background-color: gold;
       padding-top: 5px;


   }

</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto ">
            <h3>Customer login </h3><hr>
            <form action="" method="POST">
             {% csrf_token %}
              {{form.as_p}}
              <button class="btn btn-success">Dkhal awzon</button>
                {% if error %}
               <li style="color: #f60404">{{error}}</li>
                {% endif   %}

            </form>
               <p>or m3ndakch compt tsjal <a href="{% url 'appstore:customerregistration' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">tsjal hna</a> </p>
        </div>
    </div>
</div>


{% endblock %}

templates/customerorderdeatail.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Profile{% endblock  %}

{% block content%}
<div class="container">
<div class="row">
    <div class="col-md-8 mx-auto">
        <h3>order detail</h3>
            <p><span class="font-weight-bold">Order-ID:</span>{{ord_obj.id}}</p>
            <p><span class="font-weight-bold">Status:</span>{{ord_obj.order_status}}</p>
            <p><span class="font-weight-bold">Order on:</span>{{ord_obj.created_at}}({{ord_obj.created_at|timesince}}ago)</p>
            <p><span class="font-weight-bold">StatusShipping information:</span>{{ord_obj.ordered_by}}</p>
            <p><span class="font-weight-bold">Shipping address:</span>{{ord_obj.shipping_address}}</p>
            <p><span class="font-weight-bold">Mobile:</span>{{ord_obj.mobile}}</p>
            <p><span class="font-weight-bold">Email:</span>{{ord_obj.email}}</p>


    <hr>
<h4>order items info</h4>
<table class="table">
    <thead>
    <tr>
        <th>SN</th>
        <th>Items</th>
        <th>quantity</th>
        <th>rate</th>
        <th>Subtotal</th>


    </tr>
    </thead>
    <tbody>
    {% for cp in ord_obj.cart.cartproduct_set.all %}
    <tr>
    <td>{{forloop.counter}}</td>
        <td><a target="_blank" href="{% url 'appstore:productdetail' cp.product.slug %}">{{cp.product.title}}({{cp.product.id}})</a></td>
    <td>{{cp.rate}}</td>
    <td>{{cp.quantity}}</td>
    <td>{{cp.subtotal}}</td>
    </tr>
    {% endfor %}
    <tr>
        <th colspan="4" class="text-right">Total: </th>
        <th>DH: {{ord_obj.total|intcomma}}</th>
    </tr>
    </tbody>
</table>
    </div>
</div>



</div>


{% endblock %}

templates/customerprofile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock  %}
{% block content%}
<div class="container">
    <div class="row">

        <div class="col-md-4">
            <h3>detail information</h3> <hr>
            <p><span class="font-weight-bold">Name:</span>{{customer.full_name}}</p>
            <p><span class="font-weight-bold">User name:</span>{{customer.user}}</p>
            <p><span class="font-weight-bold">Email:</span>{{customer.user.email}}</p>
            <p><span class="font-weight-bold">Address:</span>{{customer.address}}</p>
            <p><span class="font-weight-bold">Join on:</span>{{customer.joined_on}}</p>



        </div>
        <div class="col-md-8">
            <h3>Previous order</h3>
          <hr>
           <table class="table">
               <thead>

               <tr>
                   <th>SN</th>
                   <th>Order ID</th>
                   <th>Amount</th>
                   <th>Ordered</th>
                   <th>Status</th>


               </tr>
           <tbody>
           {% for ord in orders %}
           <tr>
                  <td>{{forloop.counter}}</td>
                   <td> <a href="{% url 'appstore:customerorderdeatail' ord.pk %}">{{ord.id}}</a></td>
                   <td>{{ord.total}}</td>
                   <td>{{ord.created_at|timesince}} ago</td>
                    <td>{{ord.order_status}}</td>


           </tr>

           {% endfor %}

           </tbody>
               </thead>
           </table>

        </div>
    </div>
</div>

{% endblock %}

templates/customerregistration.html
{% extends 'base.html' %}
{% block title %}Registration{% endblock  %}
{% block content%}
<style>
   .errorlist{

       color: #f60404;
       background-color: gold;
       padding-top: 5px;


   }

</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto ">
            <h3>Customer registration </h3><hr>
            <form action="" method="POST">
             {% csrf_token %}
              {{form.as_p}}
              <button class="btn btn-success">tsjal awzon</button>
            </form>
               <p>dejat msjal  <a href="{% url 'appstore:customerlogin' %}">dkhal hna</a> </p>

        </div>
    </div>
</div>


{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %}home{% endblock %}
{% block content %}
<div class="container">
    <h1 class="text-center">Welcome to Chri-NyT</h1>
<hr>
<div class="row ">
    {% for p in product_list %}

    <div class="col-md-4"> <!-- style="border: 1px solid lightgrey;">--->
<h3 style="color:black;"> <a href="{% url 'appstore:productdetail' p.slug    %}">{{p.title}}</a></h3>

<!--<h3 style="color:black;">{{p.title}}</h3>-->
        <a href="{% url 'appstore:productdetail' p.slug    %}"><img src="{{p.image.url}}" height="200"></a>
        <p style="color:crimson" class="mt-3">Price:<strike>{{p.marked_price}}</strike></p>
<h1 style="color:darkorange;">{{p.selling_price}} $</h1>
<a href="{% url 'appstore:addtocart' p.id %}" class="btn btn  bg-primary">Add to cart </a>

<!--<p style="color:red;">{{p.description}}</p>-->


     </div>
    {% endfor %}
</div>
</div>

{% endblock  %}

templates/mycart.html
{% extends 'base.html' %}
{% block title %}my cart{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Items in my cart </h4>
            <hr>
            <table class="table">
                <thead>
                <tr>
                <th>SN</th>
                <th>Product</th>
                <th>Rate</th>
                <th>Quantity</th>
                <th>Subtotal</th>
                <th>Action</th>
                 </tr>

                </thead>

                <tbody>
                {% for cp in cart.cartproduct_set.all%}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{cp.product.title}}</td>
                    <td>{{cp.rate}}</td>
                    <td>{{cp.quantity}}</td>
                    <td>{{cp.subtotal}}</td>
                    <td>
                        <a href="{% url 'appstore:managecart' cp.id %}?action=inc" class="btn btn-primary">+</a>
                        <a href="{% url 'appstore:managecart' cp.id %}?action=dcr" class="btn btn-warning">-</a>
                        <a href="{% url 'appstore:managecart' cp.id %}?action=rmv" class="btn btn-danger">x</a>


                    </td>


                </tr>
                {% endfor %}
                <tr>
                    <th colspan="4" class="text-right">Total</th>
                    <th> {{cart.total}} : DH</th>
                    {% if cart.cartproduct_set.all %}
                    <th> <a class="btn btn-danger" href="{% url 'appstore:emptycart' %}">Empty cart</a></th>
                    {% endif %}

                </tr>
                     {% if cart.cartproduct_set.all %}

                <tr>
                    <th>
                        <a class="btn btn-info" href="{% url 'appstore:checkout' %}">checkout</a>
                    </th>
                </tr>
                    {% endif %}

                </tbody>

            </table>

        </div>
    </div>

</div>
{% endblock %}

templates/productdetail.html
{% extends 'base.html' %}
{% block title %}{{product.title}}{% endblock %}
{% block content %}
<div class="container">
   <h3 style="color:tomato;">Product: {{product.title}}</h3><hr>
    <div class="row">
      <div class="col-md-6">
         <img src="{{product.image.url}}" alt="" class="img-fluid">
      </div>
      <div class="col-md-6">
          <h4>{{product.title}}( viewed:{{product.view_count}})</h4>
          <h5>Category: {{product.category}}</h5>
                 <h5 style="color:crimson" class="mt-3">Price : <strike>{{product.marked_price}}</strike></h5>
                 <h1 style="color:darkorange;">{{product.selling_price}} $</h1>
                 <a href="{% url 'appstore:addtocart' product.id %}" class="btn btn-info">Add to cart </a>
         <hr>
                  <p class="text-info" >Warranty: {{product.Warranty}}</p>
                  <p class="text-info">return_policy: {{product.return_policy}}</p>
         <hr>
                  <p >{{product.description}}</p>

      </div>
    </div>

</div>







{% endblock  %}